project:
  type: abnt-thesis

abnt:
  capa:
  ficha:
  folha:
  dedicatoria:
  agradecimentos:
  epigrafe:
  resumos:
  abreviaturas:
  simbolos:

book:
  title: "Modelo Canônico de Tese ABNT"
  author: "Fred Guth"
  date: "2022-10-12"
  date-format: YYYY
  chapters:
    - index.qmd
    - Chapters/introducao.qmd
    - summary.qmd
    - references.qmd
  site-url: https://fredguth.github.io/abnt/
  repo-url: https://github.com/fredguth/abnt/exemplo
  repo-actions: [edit, source, issue]
  search: true

bibliography: referencias.bib

# Code execution settings in the case of inserted code notebooks and snippets
execute:
  echo: false
  code-overflow: wrap

format:
  html:
    theme: cosmo
  pdf:
    keep-tex: true  # remover após desenvolvimento
# 
# project:
#   type: book
#   output-dir: .
#   output-file: "Thesis"

# book:
#   title: A doctoral thesis title
#   author:
#     name: Jane Doe
#     url: http://www.janedoe.com
#   supervisor: 
#     name: Dr. Ashok Kunil
#     url: http://www.ashok.com
#   degree-name: Doctor of Philosophy
#   cover-image: images/logo.png
#   downloads: [pdf]
#   university: University of Ottawa
#   department: Department of Mathematics
#   group: Informatics Program
#   faculty: Applied Math Group

#   declaration: "Frontmatter/declaration.tex"
#   quotation:
#     text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
#     attribution: Dave Barry
#   acknowledgements: "Frontmatter/acknowledgements.tex"
#   abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis volutpat. Donec ornare libero vel velit malesuada consectetur. Vestibulum in sem non justo dignissim congue at quis erat. Integer quis erat vitae mi maximus fringilla tristique nec odio. Morbi non ipsum sapien. Vestibulum tortor est, ultricies in eros et, bibendum iaculis justo. Cras pellentesque enim quam, id pretium lacus lacinia non. Integer velit neque, ultrices a malesuada vel, imperdiet quis enim. Quisque eu facilisis urna, ut faucibus lorem. Donec mollis turpis sed arcu venenatis interdum. Nulla facilisis tortor ac scelerisque consequat."
#   abbreviations: "Frontmatter/abbreviations.tex"
#   symbols: "Frontmatter/symbols.tex"
#   dedication: "Frontmatter/dedication.tex"
#   chapters:
#     - index.qmd
#     - Chapters/Chapter2.qmd
#     - references.qmd
#   appendices:
#     - Appendices/AppendixA.qmd

#   site-url: https://nmfs-opensci.github.io/quarto-thesis/
#   repo-url: https://github.com/nmfs-opensci/quarto-thesis
#   repo-actions: [edit, source, issue]
#   search: true

# bibliography: [example.bib]

# execute:
#   echo: false
#   code-overflow: wrap

# format:
#   quarto-thesis-pdf: 
#     urlcolor: blue
#     toc-depth: 2
